const COORDINATE_ROUND = 5;

const CENTER_TOKYO = {
  lat: 35.69034,
  lng: 139.75175,
};
const MAP_ZOOM = 12;

const ADVERT_QUANTITY = 10;

const ESC_KEYCODE = 'Escape';

export {COORDINATE_ROUND, CENTER_TOKYO, MAP_ZOOM, ADVERT_QUANTITY, ESC_KEYCODE};

